on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            jobs.csv
          sparse-checkout-cone-mode: false
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          curl --data-binary @jobs.csv https://csvjson.fermyon.app/ > data.json
          git add .
          git commit -m "generated"
          git push
